Prevent data race in TestWait
Even without shuffle test, I have locally this error because of
concurrent writing.

```
=== RUN   TestWait
    client_test.go:469: got request /namespaces/default/pods POST
    client_test.go:469: got request /namespaces/default/pods POST
==================
WARNING: DATA RACE
Write at 0x00c0002fa0c0 by goroutine 44:
  k8s.io/client-go/rest/fake.(*RESTClient).do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:113 +0x4c
  k8s.io/client-go/rest/fake.(*RESTClient).do-fm()
      <autogenerated>:1 +0x3c
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0x43c
  k8s.io/client-go/rest.(*Request).request()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1228 +0x264
  k8s.io/client-go/rest.(*Request).Do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1275 +0x11c
  k8s.io/cli-runtime/pkg/resource.(*Helper).createResource()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:246 +0x148
  k8s.io/cli-runtime/pkg/resource.(*Helper).CreateWithOptions()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:237 +0x31c
  k8s.io/cli-runtime/pkg/resource.(*Helper).Create()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:207 +0x1f4
  helm.sh/helm/v4/pkg/kube.createResource.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:602 +0x30
  k8s.io/client-go/util/retry.OnError.func1()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:51 +0x40
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/wait.go:145 +0x50
  k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:461 +0x58
  k8s.io/client-go/util/retry.OnError()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:50 +0xc0
  k8s.io/client-go/util/retry.RetryOnConflict()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:104 +0xc4
  helm.sh/helm/v4/pkg/kube.createResource()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:599 +0x1c
  helm.sh/helm/v4/pkg/kube.batchPerform.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:592 +0x48
  helm.sh/helm/v4/pkg/kube.batchPerform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:594 +0x44

Previous write at 0x00c0002fa0c0 by goroutine 46:
  k8s.io/client-go/rest/fake.(*RESTClient).do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:113 +0x4c
  k8s.io/client-go/rest/fake.(*RESTClient).do-fm()
      <autogenerated>:1 +0x3c
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0x43c
  k8s.io/client-go/rest.(*Request).request()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1228 +0x264
  k8s.io/client-go/rest.(*Request).Do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1275 +0x11c
  k8s.io/cli-runtime/pkg/resource.(*Helper).createResource()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:246 +0x148
  k8s.io/cli-runtime/pkg/resource.(*Helper).CreateWithOptions()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:237 +0x31c
  k8s.io/cli-runtime/pkg/resource.(*Helper).Create()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:207 +0x1f4
  helm.sh/helm/v4/pkg/kube.createResource.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:602 +0x30
  k8s.io/client-go/util/retry.OnError.func1()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:51 +0x40
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/wait.go:145 +0x50
  k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:461 +0x58
  k8s.io/client-go/util/retry.OnError()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:50 +0xc0
  k8s.io/client-go/util/retry.RetryOnConflict()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:104 +0xc4
  helm.sh/helm/v4/pkg/kube.createResource()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:599 +0x1c
  helm.sh/helm/v4/pkg/kube.batchPerform.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:592 +0x48
  helm.sh/helm/v4/pkg/kube.batchPerform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:594 +0x44

Goroutine 44 (running) created at:
  helm.sh/helm/v4/pkg/kube.batchPerform()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:591 +0x6c
  helm.sh/helm/v4/pkg/kube.perform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:549 +0x64

Goroutine 46 (running) created at:
  helm.sh/helm/v4/pkg/kube.batchPerform()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:591 +0x6c
  helm.sh/helm/v4/pkg/kube.perform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:549 +0x64
==================
    client_test.go:469: got request /namespaces/default/pods POST
==================
WARNING: DATA RACE
Write at 0x00c000701f38 by goroutine 46:
  helm.sh/helm/v4/pkg/kube.TestWait.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client_test.go:510 +0x958
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0xb0
  k8s.io/client-go/rest/fake.(*RESTClient).do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:115 +0x9c
  k8s.io/client-go/rest/fake.(*RESTClient).do-fm()
      <autogenerated>:1 +0x3c
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0x43c
  k8s.io/client-go/rest.(*Request).request()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1228 +0x264
  k8s.io/client-go/rest.(*Request).Do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1275 +0x11c
  k8s.io/cli-runtime/pkg/resource.(*Helper).createResource()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:246 +0x148
  k8s.io/cli-runtime/pkg/resource.(*Helper).CreateWithOptions()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:237 +0x31c
  k8s.io/cli-runtime/pkg/resource.(*Helper).Create()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:207 +0x1f4
  helm.sh/helm/v4/pkg/kube.createResource.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:602 +0x30
  k8s.io/client-go/util/retry.OnError.func1()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:51 +0x40
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/wait.go:145 +0x50
  k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:461 +0x58
  k8s.io/client-go/util/retry.OnError()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:50 +0xc0
  k8s.io/client-go/util/retry.RetryOnConflict()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:104 +0xc4
  helm.sh/helm/v4/pkg/kube.createResource()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:599 +0x1c
  helm.sh/helm/v4/pkg/kube.batchPerform.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:592 +0x48
  helm.sh/helm/v4/pkg/kube.batchPerform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:594 +0x44

Previous write at 0x00c000701f38 by goroutine 45:
  helm.sh/helm/v4/pkg/kube.TestWait.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client_test.go:510 +0x958
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0xb0
  k8s.io/client-go/rest/fake.(*RESTClient).do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:115 +0x9c
  k8s.io/client-go/rest/fake.(*RESTClient).do-fm()
      <autogenerated>:1 +0x3c
  k8s.io/client-go/rest/fake.roundTripperFunc.RoundTrip()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/fake/fake.go:43 +0x34
  net/http.send()
      /usr/local/go/src/net/http/client.go:259 +0x66c
  net/http.(*Client).send()
      /usr/local/go/src/net/http/client.go:180 +0x104
  net/http.(*Client).do()
      /usr/local/go/src/net/http/client.go:728 +0xdd4
  net/http.(*Client).Do()
      /usr/local/go/src/net/http/client.go:587 +0x43c
  k8s.io/client-go/rest.(*Request).request()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1228 +0x264
  k8s.io/client-go/rest.(*Request).Do()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/rest/request.go:1275 +0x11c
  k8s.io/cli-runtime/pkg/resource.(*Helper).createResource()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:246 +0x148
  k8s.io/cli-runtime/pkg/resource.(*Helper).CreateWithOptions()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:237 +0x31c
  k8s.io/cli-runtime/pkg/resource.(*Helper).Create()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/cli-runtime@v0.32.2/pkg/resource/helper.go:207 +0x1f4
  helm.sh/helm/v4/pkg/kube.createResource.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:602 +0x30
  k8s.io/client-go/util/retry.OnError.func1()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:51 +0x40
  k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/wait.go:145 +0x50
  k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/apimachinery@v0.32.2/pkg/util/wait/backoff.go:461 +0x58
  k8s.io/client-go/util/retry.OnError()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:50 +0xc0
  k8s.io/client-go/util/retry.RetryOnConflict()
      /Users/benoit.tigeot/go/pkg/mod/k8s.io/client-go@v0.32.2/util/retry/util.go:104 +0xc4
  helm.sh/helm/v4/pkg/kube.createResource()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:599 +0x1c
  helm.sh/helm/v4/pkg/kube.batchPerform.func1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:592 +0x48
  helm.sh/helm/v4/pkg/kube.batchPerform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:594 +0x44

Goroutine 46 (running) created at:
  helm.sh/helm/v4/pkg/kube.batchPerform()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:591 +0x6c
  helm.sh/helm/v4/pkg/kube.perform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:549 +0x64

Goroutine 45 (running) created at:
  helm.sh/helm/v4/pkg/kube.batchPerform()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:591 +0x6c
  helm.sh/helm/v4/pkg/kube.perform.gowrap1()
      /Users/benoit.tigeot/projects/lifen/helm/pkg/kube/client.go:549 +0x64
==================
    client_test.go:469: got request /api/v1/namespaces/default/pods/starfish GET
    client_test.go:469: got request /api/v1/namespaces/default/pods/starfish GET
    client_test.go:469: got request /api/v1/namespaces/default/pods/starfish GET
    client_test.go:469: got request /api/v1/namespaces/default/pods/starfish GET
    client_test.go:469: got request /api/v1/namespaces/default/pods/otter GET
    client_test.go:469: got request /api/v1/namespaces/default/pods/squid GET
    testing.go:1490: race detected during execution of test
--- FAIL: TestWait (6.04s)
```

Creating them one by one, fix the issue.

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>